spring.application.name=api-gateway
server.port=8082
spring.config.import=optional:configserver

spring.cloud.gateway.server.webmvc.routes[0].id=resource-server-users
spring.cloud.gateway.server.webmvc.routes[0].uri=http://kiroff-host.brandmaker.bg:8765
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/users/**
spring.cloud.gateway.server.webmvc.routes[0].predicates[1]=Method=GET,POST
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=RemoveRequestHeader=Cookie

spring.cloud.gateway.server.webmvc.routes[1].id=resource-server-tokens
spring.cloud.gateway.server.webmvc.routes[1].uri=http://kiroff-host.brandmaker.bg:8765
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/tokens/**, Methods=GET
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=RemoveRequestHeader=Cookie

#logging.level.org.springframework.cloud.gateway=TRACE
#logging.level.org.springframework.web=DEBUG