spring.application.name=api-gateway
server.port=8082
spring.config.import=optional:configserver

eureka.client.service-url.defaultZone=http://localhost:8010/eureka
eureka.instance.instance-id=${spring.application.name}:${instanceId:${random.value}}

spring.cloud.gateway.server.webmvc.routes[0].id=resource-server-users
#spring.cloud.gateway.server.webmvc.routes[0].uri=http://kiroff-host.brandmaker.bg:8765
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://resource-server
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/users/**
spring.cloud.gateway.server.webmvc.routes[0].predicates[1]=Method=GET,POST
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=RemoveRequestHeader=Cookie

spring.cloud.gateway.server.webmvc.routes[1].id=resource-server-tokens
#spring.cloud.gateway.server.webmvc.routes[1].uri=http://kiroff-host.brandmaker.bg:8765
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://resource-server
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/tokens/**, Methods=GET
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=RemoveRequestHeader=Cookie


spring.cloud.gateway.server.webmvc.routes[2].id=resource-server-albums
#spring.cloud.gateway.server.webmvc.routes[2].uri=http://kiroff-host.brandmaker.bg:8765
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://resource-server
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/tokens/**, Methods=GET
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=RemoveRequestHeader=Cookie
#spring.cloud.gateway.server.webmvc.routes[2].filters[1]=RequestRateLimiter=1, 2r/s

spring.cloud.gateway.server.webmvc.routes[3].id=photo-album-client
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://resource-server
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/albums, Methods=GET
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.server.webmvc.routes[3].predicates[1]=Path=/albums/**, Methods=GET
spring.cloud.gateway.server.webmvc.routes[3].filters[1]=RemoveRequestHeader=Cookie

#logging.level.org.springframework.cloud.gateway=TRACE
#logging.level.org.springframework.web=DEBUG